[package]
name = "functional_macros"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"

[dependencies.syn]
version = "2.0"
default-features = false
features = [
  "clone-impls",
  "full",
  "parsing",
  "printing",
  "proc-macro",
  "visit",
  "visit-mut",
]
