#[cfg(test)]
mod test;

pwcc_util::tokens! {
Tokenizer for Token with TokenError:
    r"break\b": KeywordBreak,
    r"case\b": KeywordCase,
    r"continue\b": KeywordContinue,
    r"default\b": KeywordDefault,
    r"do\b": KeywordDo,
    r"else\b": KeywordElse,
    r"extern\b": KeywordExtern,
    r"for\b": KeywordFor,
    r"goto\b": KeywordGoto,
    r"if\b": KeywordIf,
    r"int\b": KeywordInt,
    r"return\b": KeywordReturn,
    r"static\b": KeywordStatic,
    r"switch\b": KeywordSwitch,
    r"void\b": KeywordVoid,
    r"while\b": KeywordWhile,
    r"[a-zA-Z_]\w*\b": Ident(String),
    r"[0-9]+\b": Constant(isize),
    r"!=": NotEqual,
    r"%=": PercentEqual,
    r"&=": AmpersandEqual,
    r"-=": MinusEqual,
    r"/=": ForwardSlashEqual,
    r"<<=": LeftShiftEqual,
    r">>=": RightShiftEqual,
    r"\*=": StarEqual,
    r"\+=": PlusEqual,
    r"\^=": CaretEqual,
    r"\|=": PipeEqual,
    r"&&": DoubleAmpersand,
    r"--": Decrement,
    r"<<": LeftShift,
    r"<=": LessThanEqual,
    r"==": DoubleEqual,
    r">=": GreaterThanEqual,
    r">>": RightShift,
    r"\+\+": Increment,
    r"\|\|": DoublePipe,
    r"!": Exclamation,
    r"%": Percent,
    r"&": Ampersand,
    r",": Comma,
    r"-": Minus,
    r"/": ForwardSlash,
    r":": Colon,
    r";": Semicolon,
    r"<": LessThan,
    r"=": Equal,
    r">": GreaterThan,
    r"\(": OpenParen,
    r"\)": CloseParen,
    r"\*": Star,
    r"\+": Plus,
    r"\?": Question,
    r"\^": Caret,
    r"\{": OpenBrace,
    r"\|": Pipe,
    r"\}": CloseBrace,
    r"~": Tilde,
}

pub fn lex(source: &str) -> Result<Vec<(Token, Span)>, LexError> {
    let t = Tokenizer::new();
    pwcc_util::lexer::lex(source, move |s, i| t.consume_token(s, i))
}
